version: '3' 
services: 
  pyspark-jupyter: 
    image: jupyter/pyspark-notebook 
    container_name: pyspark-jupyter-container 
    user: "${UID}:${GID}"  # Add this line
    ports: 
      - "8888:8888" 
      - "4040:4040"
    volumes: 
      - "./notebooks:/home/jovyan/work/notebooks" 
      - "./notebooks/datasets:/home/jovyan/work/notebooks/datasets" 
    command: start-notebook.sh --NotebookApp.token=''